### ISSUE TITLE
ShadeTest error

### ISSUE THREAD

**Issue by KostyaSha** [KostyaSha/docker-java-shade#1]
Test fails on runtime in IDEA:

```
java.lang.LinkageError: ClassCastException: attempting to castjar:file:/Users/integer/src/github/docker-java-shade/docker-java-shade-2/target/docker-java-shade-2-0.1.0-SNAPSHOT.jar!/shade2/javax/ws/rs/client/ClientBuilder.class to jar:file:/Users/integer/src/github/docker-java-shade/docker-java-shade-2/target/docker-java-shade-2-0.1.0-SNAPSHOT.jar!/shade2/javax/ws/rs/client/ClientBuilder.class

    at shade2.javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:97)
    at shade2.com.github.dockerjava.jaxrs.DockerCmdExecFactoryImpl.init(DockerCmdExecFactoryImpl.java:169)
    at shade2.com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:130)
    at shade2.com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:47)
    at com.github.kostyasha.docker_java_shade.ShadeTest.testShading(ShadeTest.java:16)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:27)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Process finished with exit code 255
```

from maven 3.2:

```
------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.github.kostyasha.docker_java_shade.ShadeTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.297 sec <<< FAILURE!
testShading(com.github.kostyasha.docker_java_shade.ShadeTest)  Time elapsed: 1.2 sec  <<< ERROR!
java.lang.LinkageError: ClassCastException: attempting to castjar:file:/Users/integer/src/github/docker-java-shade/docker-java-shade-2/target/docker-java-shade-2-0.1.0-SNAPSHOT.jar!/shade2/javax/ws/rs/client/ClientBuilder.class to jar:file:/Users/integer/src/github/docker-java-shade/docker-java-shade-2/target/docker-java-shade-2-0.1.0-SNAPSHOT.jar!/shade2/javax/ws/rs/client/ClientBuilder.class
    at shade2.javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:97)
    at shade2.com.github.dockerjava.jaxrs.DockerCmdExecFactoryImpl.init(DockerCmdExecFactoryImpl.java:169)
    at shade2.com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:130)
    at shade2.com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:47)
    at com.github.kostyasha.docker_java_shade.ShadeTest.testShading(ShadeTest.java:16)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Tests in error:
  testShading(com.github.kostyasha.docker_java_shade.ShadeTest): ClassCastException: attempting to castjar:file:/Users/integer/src/github/docker-java-shade/docker-java-shade-2/target/docker-java-shade-2-0.1.0-SNAPSHOT.jar!/shade2/javax/ws/rs/client/ClientBuilder.class to jar:file:/Users/integer/src/github/docker-java-shade/docker-java-shade-2/target/docker-java-shade-2-0.1.0-SNAPSHOT.jar!/shade2/javax/ws/rs/client/ClientBuilder.class

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by marcuslinke** [comment]
@KostyaSha Seems the problem is that each shaded JAR contains unshaded `org.glassfish` package.

**Comment by KostyaSha** [comment]
should be easily uncomment but i bit tired :D

**Comment by KostyaSha** [comment]
Pushed to master, 
Now:

```
Running com.github.kostyasha.docker_java_shade.ShadeTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Jan 12, 2016 11:18:35 PM shade1.org.glassfish.hk2.internal.ServiceLocatorFactoryImpl getGenerator
WARNING: Cannot find a default implementation of the HK2 ServiceLocatorGenerator
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.54 sec <<< FAILURE!
testShading(com.github.kostyasha.docker_java_shade.ShadeTest)  Time elapsed: 0.463 sec  <<< ERROR!
java.lang.RuntimeException: java.lang.ClassNotFoundException: Provider shade1.org.glassfish.jersey.internal.RuntimeDelegateImpl could not be instantiated: java.lang.IllegalStateException: No generator was provided and there is no default generator registered
    at shade1.javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:152)
    at shade1.javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:120)
    at shade1.javax.ws.rs.core.UriBuilder.newInstance(UriBuilder.java:95)
    at shade1.javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:106)
    at shade1.org.glassfish.jersey.client.JerseyWebTarget.<init>(JerseyWebTarget.java:82)
    at shade1.org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:192)
    at shade1.org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:70)
    at shade1.com.github.dockerjava.jaxrs.DockerCmdExecFactoryImpl.init(DockerCmdExecFactoryImpl.java:181)
    at shade1.com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:130)
    at shade1.com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:47)
    at com.github.kostyasha.docker_java_shade.ShadeTest.testShading(ShadeTest.java:15)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.ClassNotFoundException: Provider shade1.org.glassfish.jersey.internal.RuntimeDelegateImpl could not be instantiated: java.lang.IllegalStateException: No generator was provided and there is no default generator registered
    at shade1.javax.ws.rs.ext.FactoryFinder.newInstance(FactoryFinder.java:121)
    at shade1.javax.ws.rs.ext.FactoryFinder.find(FactoryFinder.java:207)
    at shade1.javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:135)
    ... 39 more
Caused by: java.lang.IllegalStateException: No generator was provided and there is no default generator registered
    at shade1.org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.internalCreate(ServiceLocatorFactoryImpl.java:266)
    at shade1.org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.create(ServiceLocatorFactoryImpl.java:247)
    at shade1.org.glassfish.jersey.internal.inject.Injections._createLocator(Injections.java:138)
    at shade1.org.glassfish.jersey.internal.inject.Injections.createLocator(Injections.java:109)
    at shade1.org.glassfish.jersey.internal.RuntimeDelegateImpl.<init>(RuntimeDelegateImpl.java:61)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at java.lang.Class.newInstance(Class.java:442)
    at shade1.javax.ws.rs.ext.FactoryFinder.newInstance(FactoryFinder.java:117)
    ... 41 more


Results :

Tests in error: 
  testShading(com.github.kostyasha.docker_java_shade.ShadeTest): java.lang.ClassNotFoundException: Provider shade1.org.glassfish.jersey.internal.RuntimeDelegateImpl could not be instantiated: java.lang.IllegalStateException: No generator was provided and there is no default generator registered
```

**Comment by marcuslinke** [comment]
It looks like http://grepcode.com/file/repo1.maven.org/maven2/javax.ws.rs/javax.ws.rs-api/2.0/javax/ws/rs/ext/RuntimeDelegate.java#135 tries to find the class `org.glassfish.jersey.internal.RuntimeDelegateImpl` but can't as its shaded.

**Comment by KostyaSha** [comment]
Yes, but what to do? :)

**Comment by marcuslinke** [comment]
Don't know what you try to test here but why not  put unshaded `org.glassfish` package in only one jar?

**Comment by KostyaSha** [comment]
Because jvm may have multiple different `org.glassfishes` this the same question as put only one docker-java ;)  I.e. jenkins has 3 plugins with docker-java that has 3 different versions atm plus org.glassfish may be used in some other plugins.

**Comment by marcuslinke** [comment]
OK. Then it needs to be redirected via `META-INF/services` somehow. Probably shading plugin can do that?

**Comment by KostyaSha** [comment]
Shade has transformations and all services are transformed https://github.com/KostyaSha/docker-java-shade/blob/master/pom.xml#L244-L247

**Comment by KostyaSha** [comment]
Exception comes from `shade1.org.glassfish.hk2.internal.ServiceLocatorFactoryImpl#internalCreate`

```
      at shade1.org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.internalCreate(ServiceLocatorFactoryImpl.java:266)
      at shade1.org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.create(ServiceLocatorFactoryImpl.java:247)
      - locked <0x65d> (a java.lang.Object)
      at shade1.org.glassfish.jersey.internal.inject.Injections._createLocator(Injections.java:138)
      at shade1.org.glassfish.jersey.internal.inject.Injections.createLocator(Injections.java:109)
      at shade1.org.glassfish.jersey.internal.RuntimeDelegateImpl.<init>(RuntimeDelegateImpl.java:61)
      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java:-1)
      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
      at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
      at java.lang.Class.newInstance(Class.java:442)
      at shade1.javax.ws.rs.ext.FactoryFinder.newInstance(FactoryFinder.java:117)
      at shade1.javax.ws.rs.ext.FactoryFinder.find(FactoryFinder.java:207)
      at shade1.javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:135)
      at shade1.javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:120)
      - locked <0x667> (a java.lang.Object)
      at shade1.javax.ws.rs.core.UriBuilder.newInstance(UriBuilder.java:95)
      at shade1.javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:106)
      at shade1.org.glassfish.jersey.client.JerseyWebTarget.<init>(JerseyWebTarget.java:82)
      at shade1.org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:192)
      at shade1.org.glassfish.jersey.client.JerseyClient.target(JerseyClient.java:70)
      at shade1.com.github.dockerjava.jaxrs.DockerCmdExecFactoryImpl.init(DockerCmdExecFactoryImpl.java:181)
      at shade1.com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:130)
      at shade1.com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:47)
      at com.github.kostyasha.docker_java_shade.ShadeTest.testShading(ShadeTest.java:15)
```

**Comment by KostyaSha** [comment]
```
$ cat META-INF/services/org.glassfish.hk2.extension.ServiceLocatorGenerator
shade1.org.jvnet.hk2.external.generator.ServiceLocatorGeneratorImpl
```

**Comment by marcuslinke** [comment]
It would need an additional  file `META-INF/services/javax.ws.rs.ext.RuntimeDelegate` with content `shade1.org.glassfish.jersey.internal.RuntimeDelegateImpl`  in the shaded1 jar.

**Comment by KostyaSha** [comment]
```
ls -1 META-INF/services/
com.fasterxml.jackson.core.JsonFactory
com.fasterxml.jackson.core.ObjectCodec
com.github.dockerjava.api.command.DockerCmdExecFactory
javax.ws.rs.ext.MessageBodyReader
javax.ws.rs.ext.MessageBodyWriter
org.glassfish.hk2.extension.ServiceLocatorGenerator
socketfactory.spi.SocketFactory
```

**Comment by KostyaSha** [comment]
Interesting why it missing.

**Comment by KostyaSha** [comment]
But, 

```
/**
 * Default implementation of JAX-RS {@link shade1.javax.ws.rs.ext.RuntimeDelegate}.
 * The {@link shade1.javax.ws.rs.ext.RuntimeDelegate} class looks for the implementations registered
 * in META-INF/services. If no such implementation is found, this one is picked
 * as the default. Server injection binder should override this (using META-INF/services)
 * to provide an implementation that supports {@link #createEndpoint(shade1.javax.ws.rs.core.Application, java.lang.Class)}
 * method.
 *
 * @author Jakub Podlesak
 * @author Marek Potociar (marek.potociar at oracle.com)
 * @author Martin Matula (martin.matula at oracle.com)
 */
public class RuntimeDelegateImpl extends AbstractRuntimeDelegate {
```

**Comment by KostyaSha** [comment]
Happens because `defaultGenerator` is `null` in `shade1.org.glassfish.hk2.internal.ServiceLocatorFactoryImpl#ServiceLocatorFactoryImpl`

```
WARNING: Cannot find a default implementation of the HK2 ServiceLocatorGenerator
```

**Comment by marcuslinke** [comment]
Take a look at the source here: http://grepcode.com/file/repo1.maven.org/maven2/javax.ws.rs/javax.ws.rs-api/2.0/javax/ws/rs/ext/RuntimeDelegate.java#135

Default class name JAXRS_DEFAULT_RUNTIME_DELEGATE=`org.glassfish.jersey.internal.RuntimeDelegateImpl` is hardcoded there, so it needs an additional entry in services to point it to the shaded class.

**Comment by KostyaSha** [comment]
All this classes are shaded :) And field also.
If you are using IDEA you need
1) import project
2) run install (try on parent, if fails run on bosh shade modules)
3) in idea project configuration attach to test module manually 2 jars 
4) then add exception breakpoint on IllegalState and run test

**Comment by KostyaSha** [comment]
Shading changed fields

```
    public static final String JAXRS_RUNTIME_DELEGATE_PROPERTY = "shade1.javax.ws.rs.ext.RuntimeDelegate";
    private static final String JAXRS_DEFAULT_RUNTIME_DELEGATE = "shade1.org.glassfish.jersey.internal.RuntimeDelegateImpl";

```

but seems hk2-locator isn't shaded, i will recheck content, maybe something changed before 2.1.3.

**Comment by marcuslinke** [comment]
OK. Didn't know shading is modifying fields also...

**Comment by KostyaSha** [comment]
I also :) Just jumping around generated classes. As i see everything is included in shaded jar and everything is under `shade` prefix. So all classes are shaded.

**Comment by KostyaSha** [comment]
https://issues.apache.org/jira/browse/MSHADE-190 is also fixed.

**Comment by KostyaSha** [comment]
maybe https://issues.apache.org/jira/browse/MSHADE-182

**Comment by marcuslinke** [comment]
I think you are right. Class `org.glassfish.hk2.extension.ServiceLocatorGenerator` gets relocated to `shade1.org.glassfish.hk2.extension.ServiceLocatorGenerator` but the `META-INF/services/org.glassfish.hk2.extension.ServiceLocatorGenerator` file doesn't, so the implementation can't be looked up.

**Comment by KostyaSha** [comment]
https://github.com/apache/maven-plugins/pull/79
it works very well :) test passed
